version: '3'
services:
  rust-on-gray:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/rust-on-gray:cached
      # device access
      - /dev:/dev
    working_dir: /workspaces/rust-on-gray
    tty: true
    command: sleep inf
    # device access
    privileged: true
